// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_epSMAPRlSWF0mBgfSLDXPz7kRPxdtJw',
    appId: '1:933533440365:web:2c032f7d728109413b6264',
    messagingSenderId: '933533440365',
    projectId: 'chattapp-3aa43',
    authDomain: 'chattapp-3aa43.firebaseapp.com',
    storageBucket: 'chattapp-3aa43.appspot.com',
    measurementId: 'G-G04RWE0SGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEooSEDX7NPRN-A1pqY9rOH74gOe5Xtcc',
    appId: '1:933533440365:android:b068fd19cd1200883b6264',
    messagingSenderId: '933533440365',
    projectId: 'chattapp-3aa43',
    storageBucket: 'chattapp-3aa43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl42eDPybNC0FhQ8gXU9mmbPs9nQcgzro',
    appId: '1:933533440365:ios:eadb020cc75e22b23b6264',
    messagingSenderId: '933533440365',
    projectId: 'chattapp-3aa43',
    storageBucket: 'chattapp-3aa43.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl42eDPybNC0FhQ8gXU9mmbPs9nQcgzro',
    appId: '1:933533440365:ios:eadb020cc75e22b23b6264',
    messagingSenderId: '933533440365',
    projectId: 'chattapp-3aa43',
    storageBucket: 'chattapp-3aa43.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_epSMAPRlSWF0mBgfSLDXPz7kRPxdtJw',
    appId: '1:933533440365:web:49056a45999779f23b6264',
    messagingSenderId: '933533440365',
    projectId: 'chattapp-3aa43',
    authDomain: 'chattapp-3aa43.firebaseapp.com',
    storageBucket: 'chattapp-3aa43.appspot.com',
    measurementId: 'G-4KPEY0QN0M',
  );
}
